動画教材のCSVインポート機能を実装
yanbaru-expert/team_project_38 pull request #25
Opened 2020-12-28 15:16 UTC by KoyoIshikawa

## issue 10

## 実装内容

- csvインポート設定を追加
- csvインポートの処理をdb/seeds.rbに追加
  - 処理のはじめにMovieテーブルの中身を全て削除する機能を実装 

## 参考文献

- [やんばるCODE教材（CSVインポート）](https://arcane-gorge-21903.herokuapp.com/texts/217)

## チェックリスト

【補足】プルリクを出した後，クリックでチェックを入れて下さい

- [ ] GitHub で Files changed を確認
- [ ] 影響し得る範囲のローカル環境での動作確認

2020-12-28 22:07 UTC, T-Tsujii requested changes

2020-12-28 22:07 UTC, T-Tsujii commented on db/seeds.rb
> +end
独自クラスはこちらの教材のように `lib/autoloads` に作成した方がよいですね。

https://arcane-gorge-21903.herokuapp.com/texts/217

2020-12-29 04:13 UTC, KoyoIshikawa commented on db/seeds.rb
> +end
独自クラスを`lib/autoloads`の配下に作成し、読み込めるように設定しました。

2020-12-29 10:36 UTC, T-Tsujii approved these changes
LGTMです！

2020-12-29 11:06 UTC, merged