Railsテキスト教材一覧ページの実装
yanbaru-expert/team_project_38 pull request #32
Opened 2021-01-05 20:59 UTC by KoyoIshikawa

## close #15

## 実装内容

- Railsテキスト教材一覧表示機能の実装
　- `Cards`スタイルにて実装
　-  `Grid System` を導入
- 教材詳細ページ（空）で導入
　- `show`アクションの定義
　- `show.html.erb`を作成
## 参考文献

- [【公式】Bootstrap Cards](https://getbootstrap.jp/docs/4.5/components/card/)
- [【公式】Bootstrap Grid system](https://getbootstrap.jp/docs/4.5/layout/grid/)

## チェックリスト

- [ ] GitHub で Files changed を確認
- [ ] 影響し得る範囲のローカル環境での動作確認

## スクリーンショット（必要があれば）

## 備考
- 質問をスラック に投稿済み

2021-01-07 13:38 UTC, T-Tsujii requested changes

2021-01-07 13:38 UTC, T-Tsujii commented on app/views/texts/index.html.erb
> +          <%= link_to text, target: :_blank do %>
カード内の文字に下線が入ったり青文字であるのは不自然ですので，こちらでいかがでしょう。

```suggestion
          <%= link_to text, target: :_blank, class: "text-decoration-none text-dark" do %>
```

2021-01-07 20:19 UTC, KoyoIshikawa commented on app/views/texts/index.html.erb
> +          <%= link_to text, target: :_blank do %>
確かに不自然だと感じました。
修正いたします！

2021-01-08 01:25 UTC, T-Tsujii approved these changes
LGTMです！

2021-01-08 01:46 UTC, merged