Feature/flash
yanbaru-expert/team_project_38 pull request #35
Opened 2021-01-08 14:32 UTC by kumasato1992

## issue 番号
close #12

## 実装内容
- フラッシュの実装
  - フラッシュの追加
  - Bootstrap の アラート を利用  

## 参考資料
- フラッシュの実装
  - [メッセージ投稿アプリ（その3・Bootstrap）](https://arcane-gorge-21903.herokuapp.com/texts/271)

## チェックリスト
- [ ] GitHub で Files changed を確認
- [ ] 影響し得る範囲のローカル環境での動作確認

## スクリーンショット（必要があれば）

## 備考（必要があれば）

2021-01-09 15:13 UTC, nmackee commented
`<header></header>`の`<%= yield %>`は必要なんでしょうか？
無くてもいいように思ったのですがどうでしょうか?

2021-01-10 04:43 UTC, T-Tsujii requested changes

2021-01-10 04:43 UTC, T-Tsujii commented on app/views/layouts/application.html.erb
> +      <%= yield %>
`<%= yield %>`が2つになっています。こちらを削除しておきましょう。
```suggestion
```

2021-01-10 06:57 UTC, T-Tsujii approved these changes
LGTMです！
`app/views/layouts/application.html.erb.tmp`の削除をお願いします。

2021-01-10 08:33 UTC, merged